### ISSUE TITLE
Bug in handling fields with 'nil' limit

### ISSUE THREAD

**Issue by jits** [seejohnrun/database_validation#2]
Hi,

Excellent gem!

This doesn't handle fields where no limit has been set (e.g.: text fields).

I'm working around this by manually adding limits in all migrations

Jits

**Comment by seejohnrun** [comment]
Thanks Jits,
v0.0.2 just released with a fix for this issue

Glad you like the gem,
John C

**Comment by jits** [comment]
Thanks for the quick response John!

**Comment by seejohnrun** [comment]
Yep :)
