### ISSUE TITLE
Bug/issue with associations and limits

### ISSUE THREAD

**Issue by jits** [seejohnrun/database_validation#3]
Hi again,

Seems like there is an issue with associations and limits...

```
Validation failed: Submitter is too long (maximum is 4 characters)
```

I think this is because the 'limit' for integer fields is set to '4', but this is 4 **bytes**, not 4 **characters** [1]. The `validates_length_of :maximum` assumes characters only.

Apologies for not providing a patch.

Jits

[1] http://stackoverflow.com/questions/354305/in-rails-migrations-what-does-the-number-specified-for-limit-on-an-integer-repr

**Comment by jits** [comment]
Could potentially check for `@type=:integer` (in the `Mysql2Column` object).

**Comment by seejohnrun** [comment]
Swapped out `validates_length_of` for `validates_numericality_of` and calcualted min/max from byte size

http://dev.mysql.com/doc/refman/5.0/en/numeric-types.html

v0.0.3
thanks again!

**Comment by jits** [comment]
Ace!!
