### ISSUE TITLE
Bug in handling boolean

### ISSUE THREAD

**Issue by jits** [seejohnrun/database_validation#4]
Hello again :)

This time there's an issue with handling boolean fields. I get this error:

```
undefined method `size' for true:TrueClass
```

... which I think implies that a `.size` check is being done on the value when the validation is being run.

Maybe a `validates_length_of` check is not required for boolean fields?

Cheers,
Jits

**Comment by seejohnrun** [comment]
Fixed in 0.0.4
Thanks again

**Comment by jits** [comment]
Excellent, works now, thanks!!
