### ISSUE TITLE
Bug in handling boolean (part 2)

### ISSUE THREAD

**Issue by jits** [seejohnrun/database_validation#5]
Hello again :)

This time a different issue with handling boolean fields in the db...

I believe that `validates_presence_of` on a boolean field **_may**_ be causing an issue when the value of the field is `false`. I get the validation error "can't be blank" which implies that Rails is calling `.blank?` as part of the validation process.

Cheers,
Jits

**Comment by seejohnrun** [comment]
Switched over to validates_inclusion_of in v0.0.5
Thanks!

**Comment by jits** [comment]
Whoa, that was quick!

Thanks!

**Comment by seejohnrun** [comment]
Yep - thanks for the reports
